# Generated by Django 4.0.3 on 2023-01-07 01:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('discount', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('order', models.IntegerField(default=1)),
                ('rating', models.IntegerField(default=5)),
                ('country_of_origin', models.CharField(default='Nigeria', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('colour', models.CharField(default='N/A', max_length=15)),
                ('avatar', models.ImageField(default='cart.jpg', null=True, upload_to='')),
                ('total', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
