# Generated by Django 4.0.5 on 2022-07-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_customer_remove_product_size_and_more'),
        ('store', '0017_auto_20220627_0458'),
    ]

    operations = [
    ]
